"""
Project service — manages research projects (model workspaces).

Each project lives on disk at workspaces/{user_id}/projects/{slug}/
and contains auto-generated Python notebook cells plus metadata.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent.parent / "workspaces"

# ── GPU tiers (matches Modal offerings) ───────────────────────────

GPU_TIERS = [
    {"id": "cpu",      "name": "CPU Only",           "vram": "—",     "price_hr": 0.00, "desc": "No GPU — CPU only execution"},
    {"id": "t4",       "name": "NVIDIA T4",          "vram": "16 GB", "price_hr": 0.59, "desc": "Inference & small fine-tuning"},
    {"id": "l4",       "name": "NVIDIA L4",          "vram": "24 GB", "price_hr": 0.73, "desc": "Efficient inference workloads"},
    {"id": "a10g",     "name": "NVIDIA A10G",        "vram": "24 GB", "price_hr": 1.10, "desc": "Medium models & LoRA training"},
    {"id": "a100-40",  "name": "NVIDIA A100 40 GB",  "vram": "40 GB", "price_hr": 2.78, "desc": "High-performance training"},
    {"id": "a100-80",  "name": "NVIDIA A100 80 GB",  "vram": "80 GB", "price_hr": 3.72, "desc": "Large models & full fine-tuning"},
    {"id": "h100",     "name": "NVIDIA H100",        "vram": "80 GB", "price_hr": 4.76, "desc": "Enterprise — fastest training"},
]


# ── Helpers ───────────────────────────────────────────────────────

def _slug(model_id: str) -> str:
    return model_id.replace("/", "--").replace(" ", "-").lower()


def _project_dir(user_id: int, slug: str) -> Path:
    return WORKSPACE_ROOT / str(user_id) / "projects" / slug


# ── CRUD ──────────────────────────────────────────────────────────

def create_project(
    user_id: int,
    model_id: str,
    model_name: str,
    task: str,
    tags: list[str],
    parameter_count: str = "",
    description: str = "",
) -> dict[str, Any]:
    """Create a new research project with auto-generated notebook cells."""
    slug = _slug(model_id)
    pdir = _project_dir(user_id, slug)
    pdir.mkdir(parents=True, exist_ok=True)

    project_id = uuid.uuid4().hex[:12]
    cells = _generate_cells(model_id, model_name, task, tags, parameter_count, description)

    meta: dict[str, Any] = {
        "id": project_id,
        "slug": slug,
        "model_id": model_id,
        "model_name": model_name,
        "task": task,
        "tags": tags,
        "parameter_count": parameter_count,
        "description": description,
        "gpu_tier": "t4",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "cells": cells,
    }

    # Write project.json
    (pdir / "project.json").write_text(json.dumps(meta, indent=2))

    # Write individual .py files for the folder view
    for i, cell in enumerate(cells):
        safe = cell["title"].lower().replace(" ", "_").replace("&", "and").replace("/", "_")
        fname = f"{i:02d}_{safe}.py"
        (pdir / fname).write_text(cell["code"])

    # Write requirements.txt
    reqs = _requirements_for_task(task)
    (pdir / "requirements.txt").write_text(reqs)

    # Write README
    readme = f"# {model_name}\n\n**Model:** `{model_id}`  \n**Task:** {task}  \n**Parameters:** {parameter_count}\n\n{description}\n\n---\nAuto-generated by TOLLABS Editor.\n"
    (pdir / "README.md").write_text(readme)

    return meta


def create_project_from_code(
    user_id: int,
    name: str,
    code: str,
    description: str = "",
) -> dict[str, Any]:
    """Create a project from raw strategy code (Studio → Editor flow)."""
    slug = name.lower().replace(" ", "-").replace("/", "-")[:60]
    slug = _slug(slug)
    pdir = _project_dir(user_id, slug)
    pdir.mkdir(parents=True, exist_ok=True)

    project_id = uuid.uuid4().hex[:12]
    cells = [
        {"title": "Strategy", "code": code},
    ]

    meta: dict[str, Any] = {
        "id": project_id,
        "slug": slug,
        "model_id": "",
        "model_name": name,
        "task": "strategy",
        "tags": ["studio", "strategy"],
        "parameter_count": "",
        "description": description,
        "gpu_tier": "cpu",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "cells": cells,
    }

    (pdir / "project.json").write_text(json.dumps(meta, indent=2))
    (pdir / "00_strategy.py").write_text(code)
    (pdir / "requirements.txt").write_text("numpy>=1.24.0\npandas>=2.0.0\n")
    (pdir / "README.md").write_text(
        f"# {name}\n\n{description}\n\n---\nCreated from TOLLABS Studio.\n"
    )

    return meta


def list_projects(user_id: int) -> list[dict[str, Any]]:
    """List all projects for a user (lightweight — no cells)."""
    projects_dir = WORKSPACE_ROOT / str(user_id) / "projects"
    if not projects_dir.exists():
        return []

    results = []
    for d in sorted(projects_dir.iterdir()):
        meta_path = d / "project.json"
        if not meta_path.exists():
            continue
        meta = json.loads(meta_path.read_text())
        # Return lightweight summary (no cells)
        results.append({
            "id": meta.get("id", ""),
            "slug": meta.get("slug", d.name),
            "model_id": meta.get("model_id", ""),
            "model_name": meta.get("model_name", d.name),
            "task": meta.get("task", ""),
            "tags": meta.get("tags", []),
            "parameter_count": meta.get("parameter_count", ""),
            "gpu_tier": meta.get("gpu_tier", "t4"),
            "created_at": meta.get("created_at", ""),
            "file_count": len([f for f in d.iterdir() if f.is_file() and f.name != "project.json"]),
        })
    return results


def get_project(user_id: int, slug: str) -> dict[str, Any] | None:
    """Get full project details including cells and files."""
    pdir = _project_dir(user_id, slug)
    meta_path = pdir / "project.json"
    if not meta_path.exists():
        return None

    meta = json.loads(meta_path.read_text())

    # Enumerate files
    files = []
    for f in sorted(pdir.iterdir()):
        if f.is_file() and f.name != "project.json":
            files.append({
                "name": f.name,
                "size": f.stat().st_size,
                "type": f.suffix.lstrip(".") or "file",
            })
    meta["files"] = files
    return meta


def get_project_file(user_id: int, slug: str, filename: str) -> str | None:
    """Read a single file from a project."""
    fpath = _project_dir(user_id, slug) / filename
    if not fpath.exists():
        return None
    return fpath.read_text()


def save_project_cells(user_id: int, slug: str, cells: list[dict]) -> bool:
    """Save updated cells back to the project."""
    pdir = _project_dir(user_id, slug)
    meta_path = pdir / "project.json"
    if not meta_path.exists():
        return False

    meta = json.loads(meta_path.read_text())
    meta["cells"] = cells
    (pdir / "project.json").write_text(json.dumps(meta, indent=2))
    return True


def update_gpu_tier(user_id: int, slug: str, gpu_tier: str) -> bool:
    """Update the selected GPU tier for a project."""
    pdir = _project_dir(user_id, slug)
    meta_path = pdir / "project.json"
    if not meta_path.exists():
        return False

    meta = json.loads(meta_path.read_text())
    meta["gpu_tier"] = gpu_tier
    (pdir / "project.json").write_text(json.dumps(meta, indent=2))
    return True


# ── Code generation ──────────────────────────────────────────────

def _generate_cells(
    model_id: str,
    model_name: str,
    task: str,
    tags: list[str],
    parameter_count: str,
    description: str,
) -> list[dict[str, str]]:
    """Generate notebook cells appropriate for the model's task."""
    if task in ("sentiment-analysis", "text-classification"):
        return _cells_classification(model_id, model_name, task, tags, parameter_count, description)
    elif task == "text-generation":
        return _cells_generation(model_id, model_name, tags, parameter_count, description)
    elif task == "time-series-forecasting":
        return _cells_timeseries(model_id, model_name, tags, parameter_count, description)
    else:
        return _cells_generic(model_id, model_name, task, tags, parameter_count, description)


def _cells_classification(model_id: str, model_name: str, task: str, tags: list[str], param_count: str, desc: str) -> list[dict]:
    return [
        {
            "title": "Setup & Install",
            "code": f'''# ── {model_name} — Setup ──────────────────────────────────────
# Task: {task} | Params: {param_count}
# {desc[:120]}

# Install required packages
!pip install transformers torch datasets peft accelerate scikit-learn -q

import warnings
warnings.filterwarnings("ignore")
print("✓ Dependencies ready")''',
        },
        {
            "title": "Load Model",
            "code": f'''# ── Load Pre-trained Model ───────────────────────────────────
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
import torch

MODEL_ID = "{model_id}"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_ID)

print(f"Model: {{MODEL_ID}}")
print(f"Parameters: {{sum(p.numel() for p in model.parameters()):,}}")
print(f"Labels: {{model.config.id2label}}")
print(f"Device: {{next(model.parameters()).device}}")''',
        },
        {
            "title": "Inspect Architecture",
            "code": f'''# ── Model Architecture & Config ──────────────────────────────
print("═" * 60)
print(f"Architecture: {{model.config.architectures}}")
print(f"Hidden size:  {{model.config.hidden_size}}")
print(f"Num layers:   {{model.config.num_hidden_layers}}")
print(f"Attention heads: {{model.config.num_attention_heads}}")
print(f"Vocab size:   {{model.config.vocab_size}}")
print(f"Max position:  {{getattr(model.config, 'max_position_embeddings', 'N/A')}}")
print("═" * 60)

# Layer breakdown
for name, param in model.named_parameters():
    print(f"  {{name:50s}} {{str(list(param.shape)):>20s}}  {{param.numel():>10,}} params")''',
        },
        {
            "title": "Quick Inference",
            "code": f'''# ── Quick Inference — Test Predictions ────────────────────────
pipe = pipeline("text-classification", model=model, tokenizer=tokenizer)

test_headlines = [
    "Apple stock surges 5% after record earnings beat expectations",
    "Federal Reserve raises interest rates amid growing recession fears",
    "Company files for bankruptcy protection after accounting fraud",
    "Tech sector shows strong growth in Q4, beating analyst estimates",
    "Oil prices plummet 8% on global oversupply concerns",
    "New trade deal boosts emerging market currencies to yearly highs",
]

print("── Sentiment Analysis Results ──")
print(f"{{' ':>6}} {{'Label':>12}}  {{'Score':>7}}  Headline")
print("─" * 80)
for i, headline in enumerate(test_headlines, 1):
    result = pipe(headline)[0]
    label = result["label"]
    score = result["score"]
    bar = "█" * int(score * 20)
    print(f"  [{{i}}]  {{label:>12}}  {{score:.4f}}  {{headline[:55]}}")''',
        },
        {
            "title": "Load & Prepare Dataset",
            "code": f'''# ── Dataset Preparation ──────────────────────────────────────
from datasets import load_dataset

# Financial PhraseBank — widely used financial sentiment dataset
dataset = load_dataset("financial_phrasebank", "sentences_allagree", split="train")

print(f"Dataset: financial_phrasebank (sentences_allagree)")
print(f"Samples: {{len(dataset):,}}")
print(f"Columns: {{dataset.column_names}}")
print(f"Label distribution:")
import collections
counts = collections.Counter(dataset["label"])
for label, count in sorted(counts.items()):
    pct = count / len(dataset) * 100
    bar = "█" * int(pct / 2)
    print(f"  {{label}}: {{count:>5}} ({{pct:.1f}}%) {{bar}}")

# Split into train / eval
splits = dataset.train_test_split(test_size=0.2, seed=42)
train_ds = splits["train"]
eval_ds  = splits["test"]
print(f"\\nTrain: {{len(train_ds):,}} | Eval: {{len(eval_ds):,}}")''',
        },
        {
            "title": "Tokenize Dataset",
            "code": '''# ── Tokenize for Model ───────────────────────────────────────
def tokenize_fn(examples):
    return tokenizer(
        examples["sentence"],
        padding="max_length",
        truncation=True,
        max_length=128,
    )

train_tok = train_ds.map(tokenize_fn, batched=True, remove_columns=["sentence"])
eval_tok  = eval_ds.map(tokenize_fn, batched=True, remove_columns=["sentence"])

print(f"✓ Tokenized")
print(f"  Train features: {list(train_tok.features.keys())}")
print(f"  Sequence length: 128 tokens")
print(f"  Sample input_ids shape: {train_tok[0]['input_ids'][:10]}...")''',
        },
        {
            "title": "Evaluate Baseline",
            "code": '''# ── Evaluate Baseline Performance ────────────────────────────
import numpy as np
from sklearn.metrics import classification_report, accuracy_score
from transformers import Trainer, TrainingArguments

eval_args = TrainingArguments(
    output_dir="./eval_tmp",
    per_device_eval_batch_size=64,
    report_to="none",
    logging_steps=9999,
)

trainer = Trainer(model=model, args=eval_args)
predictions = trainer.predict(eval_tok)
preds = np.argmax(predictions.predictions, axis=-1)

print("── Baseline Performance (before fine-tuning) ──")
print(classification_report(eval_tok["label"], preds, digits=4))
baseline_acc = accuracy_score(eval_tok["label"], preds)
print(f"Baseline Accuracy: {baseline_acc:.4f}")''',
        },
        {
            "title": "LoRA Fine-Tuning Setup",
            "code": '''# ── Fine-Tuning with LoRA (Parameter-Efficient) ─────────────
from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=16,                   # rank
    lora_alpha=32,          # scaling
    lora_dropout=0.1,
    bias="none",
    target_modules=["query", "value"],  # attention layers
)

peft_model = get_peft_model(model, lora_config)
peft_model.print_trainable_parameters()
# Typically <1% of total params — fast and memory-efficient''',
        },
        {
            "title": "Train Model",
            "code": '''# ── Training Loop ────────────────────────────────────────────
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none",
    logging_steps=25,
    fp16=True,  # mixed precision — faster on GPU
)

def compute_metrics(eval_pred):
    preds = np.argmax(eval_pred.predictions, axis=-1)
    acc = accuracy_score(eval_pred.label_ids, preds)
    return {"accuracy": acc}

trainer = Trainer(
    model=peft_model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=eval_tok,
    compute_metrics=compute_metrics,
)

print("Starting fine-tuning...")
result = trainer.train()
print(f"\\n✓ Training complete")
print(f"  Total steps: {result.global_step}")
print(f"  Final loss:  {result.training_loss:.4f}")''',
        },
        {
            "title": "Evaluate Fine-Tuned",
            "code": '''# ── Post Fine-Tuning Evaluation ──────────────────────────────
ft_predictions = trainer.predict(eval_tok)
ft_preds = np.argmax(ft_predictions.predictions, axis=-1)

print("── Fine-Tuned Performance ──")
print(classification_report(eval_tok["label"], ft_preds, digits=4))
ft_acc = accuracy_score(eval_tok["label"], ft_preds)

print(f"\\n{'Metric':<20} {'Baseline':>10} {'Fine-Tuned':>12} {'Δ':>8}")
print("─" * 52)
print(f"{'Accuracy':<20} {baseline_acc:>10.4f} {ft_acc:>12.4f} {ft_acc - baseline_acc:>+8.4f}")''',
        },
        {
            "title": "Save & Export",
            "code": f'''# ── Save Fine-Tuned Model ────────────────────────────────────
OUTPUT_DIR = "./fine_tuned_{model_id.split("/")[-1]}"

peft_model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

import os
total_size = sum(
    os.path.getsize(os.path.join(OUTPUT_DIR, f))
    for f in os.listdir(OUTPUT_DIR)
    if os.path.isfile(os.path.join(OUTPUT_DIR, f))
)
print(f"✓ Model saved to {{OUTPUT_DIR}}")
print(f"  Files: {{os.listdir(OUTPUT_DIR)}}")
print(f"  Total size: {{total_size / 1024:.1f}} KB")
print()
print("Next: Click 'Save & Publish' to backtest your model →")''',
        },
    ]


def _cells_generation(model_id: str, model_name: str, tags: list[str], param_count: str, desc: str) -> list[dict]:
    return [
        {
            "title": "Setup & Install",
            "code": f'''# ── {model_name} — Text Generation ─────────────────────────
# Params: {param_count} | Tags: {", ".join(tags)}
# {desc[:120]}

!pip install transformers torch accelerate peft datasets -q
print("✓ Dependencies ready")''',
        },
        {
            "title": "Load Model",
            "code": f'''# ── Load Pre-trained Model ───────────────────────────────────
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

MODEL_ID = "{model_id}"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    device_map="auto",
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(f"Model: {{MODEL_ID}}")
print(f"Parameters: {{sum(p.numel() for p in model.parameters()):,}}")
print(f"Vocab size: {{model.config.vocab_size}}")
print(f"Max length: {{getattr(model.config, 'max_position_embeddings', 'N/A')}}")''',
        },
        {
            "title": "Inspect Architecture",
            "code": '''# ── Model Architecture ───────────────────────────────────────
print(f"Layers: {model.config.num_hidden_layers}")
print(f"Hidden: {model.config.hidden_size}")
print(f"Heads:  {model.config.num_attention_heads}")
print(f"Dtype:  {next(model.parameters()).dtype}")

# Memory usage
mem = sum(p.numel() * p.element_size() for p in model.parameters())
print(f"Memory: {mem / 1024**3:.2f} GB")''',
        },
        {
            "title": "Generate Text",
            "code": '''# ── Text Generation — Financial Analysis ─────────────────────
prompts = [
    "Market analysis: The Federal Reserve's decision to",
    "Trading strategy: Given the current bullish trend in tech stocks,",
    "Risk assessment: The key factors to consider when evaluating",
]

for prompt in prompts:
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        temperature=0.7,
        top_p=0.9,
        do_sample=True,
    )
    text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print(f"Prompt: {prompt}")
    print(f"Output: {text}")
    print("─" * 60)''',
        },
        {
            "title": "Prepare Dataset",
            "code": '''# ── Fine-Tuning Dataset ──────────────────────────────────────
from datasets import load_dataset

# Load a financial text dataset for fine-tuning
dataset = load_dataset("financial_phrasebank", "sentences_allagree", split="train")

# Format for causal LM
def format_fn(example):
    text = f"Analyze: {example['sentence']}\\nSentiment:"
    return {"text": text}

formatted = dataset.map(format_fn)
print(f"Dataset: {len(formatted)} samples")
print(f"Sample: {formatted[0]['text'][:100]}...")''',
        },
        {
            "title": "LoRA Fine-Tuning",
            "code": '''# ── LoRA Configuration ───────────────────────────────────────
from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
)

peft_model = get_peft_model(model, lora_config)
peft_model.print_trainable_parameters()''',
        },
        {
            "title": "Train Model",
            "code": f'''# ── Training ─────────────────────────────────────────────────
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=1e-4,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    report_to="none",
)

trainer = Trainer(
    model=peft_model,
    args=training_args,
    train_dataset=formatted,
)

print("Starting fine-tuning...")
result = trainer.train()
print(f"✓ Complete | Loss: {{result.training_loss:.4f}}")''',
        },
        {
            "title": "Save & Export",
            "code": f'''# ── Save Fine-Tuned Model ────────────────────────────────────
OUTPUT_DIR = "./fine_tuned_{model_id.split('/')[-1]}"
peft_model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

import os
print(f"✓ Model saved to {{OUTPUT_DIR}}")
print(f"  Files: {{os.listdir(OUTPUT_DIR)}}")
print("\\nNext: Click 'Save & Publish' to backtest →")''',
        },
    ]


def _cells_timeseries(model_id: str, model_name: str, tags: list[str], param_count: str, desc: str) -> list[dict]:
    return [
        {
            "title": "Setup & Install",
            "code": f'''# ── {model_name} — Time Series Forecasting ─────────────────
# Params: {param_count} | Tags: {", ".join(tags)}
# {desc[:120]}

!pip install torch transformers chronos-forecasting pandas matplotlib -q
print("✓ Dependencies ready")''',
        },
        {
            "title": "Load Model",
            "code": f'''# ── Load Pre-trained Model ───────────────────────────────────
import torch
import numpy as np
import pandas as pd

MODEL_ID = "{model_id}"

# Chronos models use a special pipeline
try:
    from chronos import ChronosPipeline
    pipeline = ChronosPipeline.from_pretrained(MODEL_ID, device_map="auto")
    print(f"✓ Loaded Chronos model: {{MODEL_ID}}")
except ImportError:
    from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_ID)
    print(f"✓ Loaded T5-based model: {{MODEL_ID}}")

print(f"Device: {{torch.device('cuda' if torch.cuda.is_available() else 'cpu')}}")''',
        },
        {
            "title": "Generate Sample Data",
            "code": '''# ── Generate Synthetic Market Data ────────────────────────────
import numpy as np
import pandas as pd

np.random.seed(42)
n = 500
dates = pd.date_range("2024-01-01", periods=n, freq="h")
trend = np.linspace(100, 120, n)
noise = np.cumsum(np.random.randn(n) * 0.3)
prices = trend + noise

df = pd.DataFrame({"date": dates, "close": prices})
df["returns"] = df["close"].pct_change()
df["volatility"] = df["returns"].rolling(20).std()

print(f"Generated {n} hourly price bars")
print(f"Price range: ${df['close'].min():.2f} — ${df['close'].max():.2f}")
print(f"Mean return: {df['returns'].mean():.6f}")
print(f"\\n{df.tail(5).to_string(index=False)}")''',
        },
        {
            "title": "Forecast",
            "code": '''# ── Run Forecast ─────────────────────────────────────────────
context = torch.tensor(df["close"].values[-200:], dtype=torch.float32)
prediction_length = 24  # forecast next 24 periods

try:
    forecast = pipeline.predict(context.unsqueeze(0), prediction_length)
    median = np.median(forecast[0].numpy(), axis=0)
    low  = np.percentile(forecast[0].numpy(), 10, axis=0)
    high = np.percentile(forecast[0].numpy(), 90, axis=0)
    print(f"Forecast ({prediction_length} steps):")
    print(f"  Median: {median[:5]}...")
    print(f"  80% CI: [{low[0]:.2f}, {high[0]:.2f}]")
except Exception as e:
    print(f"Forecast with basic approach: {e}")
    # Fallback: simple momentum forecast
    last_price = df["close"].iloc[-1]
    momentum = df["returns"].iloc[-20:].mean()
    forecast_prices = [last_price * (1 + momentum) ** i for i in range(1, prediction_length + 1)]
    print(f"Momentum forecast: {forecast_prices[:5]}")''',
        },
        {
            "title": "Evaluate Model",
            "code": '''# ── Backtest Evaluation ──────────────────────────────────────
# Walk-forward evaluation
window = 200
horizon = 24
errors = []

for start in range(0, len(df) - window - horizon, horizon):
    ctx = torch.tensor(df["close"].values[start:start + window], dtype=torch.float32)
    actual = df["close"].values[start + window:start + window + horizon]
    try:
        pred = pipeline.predict(ctx.unsqueeze(0), horizon)
        pred_median = np.median(pred[0].numpy(), axis=0)
    except:
        last = ctx[-1].item()
        pred_median = np.full(horizon, last)
    
    mae = np.mean(np.abs(pred_median[:len(actual)] - actual))
    errors.append(mae)

print(f"Walk-forward MAE: {np.mean(errors):.4f}")
print(f"Evaluations: {len(errors)}")''',
        },
        {
            "title": "Save & Export",
            "code": f'''# ── Save Results ─────────────────────────────────────────────
import json, os

OUTPUT_DIR = "./fine_tuned_{model_id.split('/')[-1]}"
os.makedirs(OUTPUT_DIR, exist_ok=True)

results = {{
    "model_id": "{model_id}",
    "mae": float(np.mean(errors)) if errors else None,
    "forecast_horizon": prediction_length,
    "context_length": window,
}}

with open(f"{{OUTPUT_DIR}}/results.json", "w") as f:
    json.dump(results, f, indent=2)

print(f"✓ Results saved to {{OUTPUT_DIR}}")
print("\\nNext: Click 'Save & Publish' to backtest →")''',
        },
    ]


def _cells_generic(model_id: str, model_name: str, task: str, tags: list[str], param_count: str, desc: str) -> list[dict]:
    return [
        {
            "title": "Setup & Install",
            "code": f'''# ── {model_name} ─────────────────────────────────────────────
# Task: {task} | Params: {param_count}
# {desc[:120]}

!pip install transformers torch datasets peft accelerate -q
print("✓ Dependencies ready")''',
        },
        {
            "title": "Load Model",
            "code": f'''# ── Load Model ───────────────────────────────────────────────
from transformers import AutoTokenizer, AutoModel

MODEL_ID = "{model_id}"
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModel.from_pretrained(MODEL_ID)

print(f"Model: {{MODEL_ID}}")
print(f"Parameters: {{sum(p.numel() for p in model.parameters()):,}}")
print(f"Config: {{model.config}}")''',
        },
        {
            "title": "Explore Model",
            "code": '''# ── Explore Model ────────────────────────────────────────────
print(model)

# Test forward pass
sample = tokenizer("Test input for model exploration", return_tensors="pt")
with torch.no_grad():
    output = model(**sample)
print(f"\\nOutput keys: {list(output.keys())}")
print(f"Output shape: {output.last_hidden_state.shape}")''',
        },
        {
            "title": "Save & Export",
            "code": f'''# ── Save Model ───────────────────────────────────────────────
OUTPUT_DIR = "./fine_tuned_{model_id.split('/')[-1]}"
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"✓ Model saved to {{OUTPUT_DIR}}")
print("\\nNext: Click 'Save & Publish' to backtest →")''',
        },
    ]


def _requirements_for_task(task: str) -> str:
    """Generate requirements.txt for the task."""
    base = "transformers>=4.36.0\ntorch>=2.1.0\ndatasets>=2.16.0\naccelerate>=0.25.0\npeft>=0.7.0\n"
    if task == "time-series-forecasting":
        base += "chronos-forecasting>=1.0.0\npandas>=2.0.0\nmatplotlib>=3.7.0\n"
    elif task in ("sentiment-analysis", "text-classification"):
        base += "scikit-learn>=1.3.0\n"
    return base
